### PR TITLE
Create verify.yml for GitHub pipeline

### PR DESCRIPTION
**Pull request by bekihm**
Add github pipeline

### CODE REVIEW

**Comment by bekihm** [comment]
Only the chromium browser will not start.. almost there..

**Comment by volkflo** [comment]
Cool :)

**Comment by bekihm** [comment]
@apiman/maintainers After a couple of commits we have now a pipeline which verifies all builds, do the browser tests and publishes the tests via github bot in the corresponding PR. What do you think about it?

**Review by EricWittmann — APPROVED** [review]
lgtm!

**Comment by volkflo** [comment]
Looks also good to me 👍

**Comment by volkflo** [comment]
Just for discussion: 
It would be nice to also push a docker image for the main branch to docker hub. Maybe "apiman/devportal:latest?

**Review by volkflo — APPROVED** [review]

**Comment by bekihm** [comment]
Yes, I think this is something for a release pipeline. This pipeline here verifies only the build of some PRs.

**Comment by volkflo** [comment]
The release workflow is done in the pipeline of the main apiman project.
We should include it there as well. But for I think it is okay if you already merge this 😊

**Comment by EricWittmann** [comment]
Yeah we could pretty easily push `latest` docker image builds from a GH Actions workflow if you think that would be useful.  I think traditionally I've only pushed docker images for releases, but I'm happy for us to expand that.

**Comment by bekihm** [comment]
@volkflo You can open another issue for pushing docker images if required.

**Comment by volkflo** [comment]
@EricWittmann Yes, I looked it up, only for the releases. But I think `latest` with the current `main/master` branch is pretty helpful to try-out new features or merged fixes :)

**Comment by volkflo** [comment]
Please see: https://github.com/apiman/apiman-developer-portal/pull/7

**Pull request merged**
