### PR TITLE
Add docker workflow for main/latest

### PR DESCRIPTION
**Pull request by volkflo**
The first draft of a docker-workflow:

I would go with the name `apiman/developer-portal`. So it may then show also up if somebody searches for `developer portal` instead of only `devportal`. 

@EricWittmann I could not look up the docker hub passwords in the main project. Maybe you can add them here or provide the secrets for the whole org, so every project could use them? :)

### CODE REVIEW

**Comment by volkflo** [comment]
Just an additional note:
image
At the moment build/test/publish runs in parallel. Not sure if we really want this?

**Comment by bekihm** [comment]
I have also seen that the jobs run parallel. But I think there is no problem with that?

**Comment by bekihm** [comment]
Maybe this helps:
https://github.community/t/waiting-for-jobs-to-finish/16730/5

So you can wait with the publish job until builds and tests are done.

**Comment by volkflo** [comment]
> Maybe this helps:
> https://github.community/t/waiting-for-jobs-to-finish/16730/5
> 
> So you can wait with the publish job until builds and tests are done.

Done, thanks :)

**Comment by EricWittmann** [comment]
Secrets added!

**Comment by EricWittmann** [comment]
I actually created a new "apimanci" docker hub user - so I'm only 95% certain that what I've done will work. :)  We'll figure it out if something goes wrong!

**Comment by volkflo** [comment]
@EricWittmann Thanks :) So I will merge this and we will see what will happen :)

**Pull request merged**
